<a href="https://colab.research.google.com/github/zhangwiki86-soton/Data-Engineering/blob/main/Farm%20data%20normalization%20python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [6]:
! git clone https://github.com/zhangwiki86-soton//Data-Engineering.git

fatal: destination path 'Data-Engineering' already exists and is not an empty directory.

In [11]:
df=pd.read_csv("/content/Data-Engineering/COMM033DA_Data_Coursework (2).csv")
df

,Farm ID,Farm Location,Crop ID,Crop Name,Planting Date,Harvest Date,Soil ID,pH Level,Nitrogen Level,Phosphorus Level,...,Resource Quantity,Date of Application,Sustainability Initiative ID,Initiative Description,Date Initiated,Expected Impact,Crop Yield,Environmental Impact Score,Water Source,Labour Hours
0,1,"South Farm, Kent",101,Wheat,15/03/2023,15/08/2023,1,6.5,50,20,...,1000,10/03/2023,1,Organic Farming,01/01/2023,Increase in yield,3000,4,River,150
1,1,"South Farm, Kent",102,Barley,16/03/2023,20/08/2023,1,6.5,50,20,...,200,12/03/2023,1,Organic Farming,01/01/2023,Increase in yield,2800,4,River,120
2,2,"Green Acres, Essex",201,Corn,10/04/2023,15/09/2023,2,6.8,40,25,...,800,05/04/2023,2,Crop Rotation,15/02/2023,Improved soil quality,1500,3,Borehole,200
3,2,"Green Acres, Essex",202,Soybeans,11/04/2023,20/09/2023,2,6.8,40,25,...,150,06/04/2023,2,Crop Rotation,15/02/2023,Improved soil quality,1200,3,Borehole,180
4,3,"Sunny Fields, Hampshire",301,Potatoes,20/03/2023,15/07/2023,3,6.2,30,15,...,1200,18/03/2023,3,Water Conservation,01/03/2023,Reduced water usage,2000,5,Rainwater,160
5,3,"Sunny Fields, Hampshire",302,Carrots,21/03/2023,20/07/2023,3,6.2,30,15,...,300,19/03/2023,3,Water Conservation,01/03/2023,Reduced water usage,2200,5,Rainwater,170
6,4,"Hilltop Farm, Yorkshire",401,Apples,05/04/2023,10/09/2023,4,6.4,45,22,...,900,02/04/2023,4,Soil Health Improvement,20/01/2023,Enhanced nutrient retention,1800,2,Well,140
7,4,"Hilltop Farm, Yorkshire",402,Pears,06/04/2023,15/09/2023,4,6.4,45,22,...,250,03/04/2023,4,Soil Health Improvement,20/01/2023,Enhanced nutrient retention,1600,2,Well,130
8,5,"Riverbend Farm, Cornwall",501,Tomatoes,25/03/2023,10/08/2023,5,6.7,55,28,...,1100,22/03/2023,5,Pesticide Reduction,10/02/2023,Less chemical runoff,2500,4,River,190
9,5,"Riverbend Farm, Cornwall",502,Lettuce,26/03/2023,15/08/2023,5,6.7,55,28,...,180,24/03/2023,5,Pesticide Reduction,10/02/2023,Less chemical runoff,2400,4,River,175

In [12]:

# FARM
# -----------------------------
farms = df[
    ['Farm ID', 'Farm Location', 'Water Source']
].drop_duplicates()

# -----------------------------
# SOIL
# -----------------------------
soils = df[
    ['Soil ID',
     'pH Level',
     'Nitrogen Level',
     'Phosphorus Level',
     'Potassium Level']
].drop_duplicates()

# -----------------------------
# CROP
# -----------------------------
crops = df[
    ['Crop ID',
     'Farm ID',
     'Soil ID',
     'Crop Name',
     'Planting Date',
     'Harvest Date',
     'Crop Yield',
     'Environmental Impact Score',
     'Labour Hours']
].drop_duplicates()

# -----------------------------
# RESOURCE
# -----------------------------
resources = df[
    ['Resource ID', 'Resource Type']
].drop_duplicates()

# -----------------------------
# RESOURCE APPLICATION
# -----------------------------
resource_applications = df[
    ['Crop ID',
     'Resource ID',
     'Resource Quantity',
     'Date of Application']
].drop_duplicates()

# -----------------------------
# INITIATIVE
# -----------------------------
initiatives = df[
    ['Sustainability Initiative ID',
     'Initiative Description',
     'Date Initiated',
     'Expected Impact']
].drop_duplicates()

# -----------------------------
# FARM INITIATIVE
# -----------------------------
farm_initiatives = df[
    ['Farm ID', 'Sustainability Initiative ID']
].drop_duplicates()

In [13]:
# Display tables
print("FARMS")
display(farms)

print("SOILS")
display(soils)

print("CROPS")
display(crops)

print("RESOURCES")
display(resources)

print("RESOURCE APPLICATIONS")
display(resource_applications)

print("INITIATIVES")
display(initiatives)

print("FARM INITIATIVES")
display(farm_initiatives)

FARMS

   Farm ID             Farm Location Water Source
0        1          South Farm, Kent        River
2        2        Green Acres, Essex     Borehole
4        3   Sunny Fields, Hampshire    Rainwater
6        4   Hilltop Farm, Yorkshire         Well
8        5  Riverbend Farm, Cornwall        River

SOILS

   Soil ID  pH Level  Nitrogen Level  Phosphorus Level  Potassium Level
0        1       6.5              50                20              180
2        2       6.8              40                25              160
4        3       6.2              30                15              150
6        4       6.4              45                22              175
8        5       6.7              55                28              200

CROPS

,Crop ID,Farm ID,Soil ID,Crop Name,Planting Date,Harvest Date,Crop Yield,Environmental Impact Score,Labour Hours
0,101,1,1,Wheat,15/03/2023,15/08/2023,3000,4,150
1,102,1,1,Barley,16/03/2023,20/08/2023,2800,4,120
2,201,2,2,Corn,10/04/2023,15/09/2023,1500,3,200
3,202,2,2,Soybeans,11/04/2023,20/09/2023,1200,3,180
4,301,3,3,Potatoes,20/03/2023,15/07/2023,2000,5,160
5,302,3,3,Carrots,21/03/2023,20/07/2023,2200,5,170
6,401,4,4,Apples,05/04/2023,10/09/2023,1800,2,140
7,402,4,4,Pears,06/04/2023,15/09/2023,1600,2,130
8,501,5,5,Tomatoes,25/03/2023,10/08/2023,2500,4,190
9,502,5,5,Lettuce,26/03/2023,15/08/2023,2400,4,175

RESOURCES

   Resource ID Resource Type
0            1         Water
1            2    Fertilizer

RESOURCE APPLICATIONS

   Crop ID  Resource ID  Resource Quantity Date of Application
0      101            1               1000          10/03/2023
1      102            2                200          12/03/2023
2      201            1                800          05/04/2023
3      202            2                150          06/04/2023
4      301            1               1200          18/03/2023
5      302            2                300          19/03/2023
6      401            1                900          02/04/2023
7      402            2                250          03/04/2023
8      501            1               1100          22/03/2023
9      502            2                180          24/03/2023

INITIATIVES

,Sustainability Initiative ID,Initiative Description,Date Initiated,Expected Impact
0,1,Organic Farming,01/01/2023,Increase in yield
2,2,Crop Rotation,15/02/2023,Improved soil quality
4,3,Water Conservation,01/03/2023,Reduced water usage
6,4,Soil Health Improvement,20/01/2023,Enhanced nutrient retention
8,5,Pesticide Reduction,10/02/2023,Less chemical runoff

FARM INITIATIVES

   Farm ID  Sustainability Initiative ID
0        1                             1
2        2                             2
4        3                             3
6        4                             4
8        5                             5